### PR TITLE
Make it compile for latest Nim

### PR DESCRIPTION
**Pull request by andreaferretti**
The literal `uint64(-1)` does not compile anymore on recent versions of Nim. I have changed all usages of `uint64(-1)` with `(not 0'u64)` and `uint64(-2)` with `(not 1'u64)`.

Also, I changed the syntax of the nimble file to nimscript, since recent versions of Nimble do not accept the old version anymore, and I consequently added a task, so that now running nimble test runs the tests.

As a minor cleanup, I removed unused imports, for which I received warnings.

### CODE REVIEW

**Comment by oprypin** [comment]
FYI: check the email address that you're using for the commits (see `git log`)  and possibly associate it with your GitHub account, so the commits link to you.

**Comment by oprypin** [comment]
For that reason, I'll wait for your confirmation first.

But this works great, all commits are nice, and I fixed Travis build in the meantime.

Thanks.

**Comment by andreaferretti** [comment]
Uh sorry, it's my other address. If you don't mind, for me it is ok to publish with this address, otherwise I would have to make yet another PR :-)

**Comment by andreaferretti** [comment]
Would you mind doing a version bump (= update version in .nimble file + git tag) to 0.5.6 so that my packages depending on nim random can refer to it?

**Comment by oprypin** [comment]
OK

**Pull request merged**
