### PR TITLE
Fixed uint64(-1) not working anymore

### PR DESCRIPTION
**Pull request by andreaferretti**
The literal `uint64(-1)` does not compile anymore on recent versions of Nim. I have changed all usages of `uint64(-1)` with `(not 0'u64)` and `uint64(-2)` with `(not 1'u64)`.

Also, I changed the syntax of the nimble file to nimscript, since recent versions of Nimble do not accept the old version anymore, and I consequently added a task, so that now running `nimble test` runs the tests.

As a minor cleanup, I removed unused imports, for which I received warnings.

### CODE REVIEW

**Comment by oprypin** [comment]
That's nice and all, but you've put two or three completely separate changes into one PR (and one commit, even).
Could you correct that, please? Thanks.

**Comment by andreaferretti** [comment]
You are right, but is it worthwhile to make all separate PRs? It is going to take a while: if you want a clean history I should make the changes to make this compile, wait for you to accept this, then clean up the imports...

If you think this is really worthwhile, I can do this, but maybe it is quicker to just go on with this version :-)

**Comment by oprypin** [comment]
You can just make separate commits.

I could even split these up myself, though me writing to the branch andreaferretti:**master** could be controversial.

I do insist on the split, though :/

Also gotta look into why Travis fails.
Might be similar to this fix
https://github.com/docopt/docopt.nim/commit/fac273695287d182548ac1507dc3a35b6801c81b

**Comment by andreaferretti** [comment]
I am not really sure how to split commits with git, so I am going to close this PR and make another one :-)

**Pull request closed without merging**
