### PR TITLE
Added random sampler using reservoir sampling.

### PR DESCRIPTION
**Pull request by oderwat**
This adds an efficient take `n` ramdom samples for unknown length iterators.

### CODE REVIEW

**Comment by BlaXpirit** [comment]
The problem here is your branch is 4 commits behind. The original changes would work if applied to the newest commit...

**Comment by oderwat** [comment]
No? There was a definition missing. Well not it works doesn't it?

**Comment by oderwat** [comment]
I also made an rebase for the current master now.

**Comment by oderwat** [comment]
Hum :) I guess you are right and the RNG was not needed (anymore). I revert it!

**Pull request merged**
